---
# tasks file for network-bonding
- name: Configure network bonding using nmcli
  hosts: all
  become: yes
  tasks:
    - name: Install NetworkManager
      ansible.builtin.package:
        name: NetworkManager
        state: present

    - name: Create bond connection
      community.general.nmcli:
        conn_name: bond0
        ifname: bond0
        type: bond
        mode: active-backup
        ip4: 192.168.1.99/24
        gw4: 192.168.1.1
        state: present

    - name: Add slave interfaces to bond
      community.general.nmcli:
        conn_name: "{{ item }}"
        ifname: "{{ item }}"
        type: bond-slave
        master: bond0
        state: present
      loop:
        - enp0s8
        - enp0s9
